/*

Checkear deportes y paises para darles a los deportistas

DELETE FROM Deportistas
GO
DBCC CHECKIDENT ([Deportistas], RESEED, 0);
GO

INSERT [dbo].[Deportistas] ([Apellido], [Nombre], [FechaNacimiento], [Foto], [IdPais], [IdDeporte], [Logros]) VALUES (N'Biles', N'Simone', CAST(N'1997-03-14' AS Date), N'https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Simone_Biles_Rio_2016e.jpg/1024px-Simone_Biles_Rio_2016e.jpg', 2, 24, N'Medallista de oro en gimnasia, 4 veces campeona olímpica')
INSERT [dbo].[Deportistas] ([Apellido], [Nombre], [FechaNacimiento], [Foto], [IdPais], [IdDeporte], [Logros]) VALUES (N'Ledecky', N'Katie', CAST(N'1997-03-17' AS Date), N'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Katie_Ledecky_at_the_2023_Golden_Goggle_Awards_%28cropped%29.jpg/474px-Katie_Ledecky_at_the_2023_Golden_Goggle_Awards_%28cropped%29.jpg', 2, 6, N'Medallista de oro en natación, 3 veces campeona olímpica')
INSERT [dbo].[Deportistas] ([Apellido], [Nombre], [FechaNacimiento], [Foto], [IdPais], [IdDeporte], [Logros]) VALUES ( N'James', N'LeBron', CAST(N'1984-12-30' AS Date), N'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/LeBron_James_%2851959977144%29_%28cropped2%29.jpg/800px-LeBron_James_%2851959977144%29_%28cropped2%29.jpg', 2, 10, N'Medallista de oro en baloncesto, 2 veces campeón olímpico')
INSERT [dbo].[Deportistas] ([Apellido], [Nombre], [FechaNacimiento], [Foto], [IdPais], [IdDeporte], [Logros]) VALUES ( N'Dressel', N'Caeleb', CAST(N'1996-08-16' AS Date), N'https://upload.wikimedia.org/wikipedia/commons/c/c9/Caeleb_Dressel_%28USA%29_2018.jpg', 2, 6, N'Medallista de oro en natación, 2 veces campeón olímpico')
INSERT [dbo].[Deportistas] ([Apellido], [Nombre], [FechaNacimiento], [Foto], [IdPais], [IdDeporte], [Logros]) VALUES ( N'Moore', N'Carissa', CAST(N'1993-08-27' AS Date), N'https://upload.wikimedia.org/wikipedia/commons/3/38/CarissaMoore2.jpg', 2, 20, N'Medallista de oro en surf, campeona mundial')
INSERT [dbo].[Deportistas] ([Apellido], [Nombre], [FechaNacimiento], [Foto], [IdPais], [IdDeporte], [Logros]) VALUES ( N'Lyles', N'Noah', CAST(N'1997-07-18' AS Date), N'https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Noah_Lyles_%28USA%29.jpg/1024px-Noah_Lyles_%28USA%29.jpg', 2, 8, N'Medallista de oro en atletismo, campeón mundial')
INSERT [dbo].[Deportistas] ([Apellido], [Nombre], [FechaNacimiento], [Foto], [IdPais], [IdDeporte], [Logros]) VALUES ( N'Gauff', N'Coco', CAST(N'2004-03-13' AS Date), N'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Coco_Gauff_%28cropped_2%29.jpg/800px-Coco_Gauff_%28cropped_2%29.jpg', 2, 12, N'Medallista de oro en tenis, joven promesa')
INSERT [dbo].[Deportistas] ([Apellido], [Nombre], [FechaNacimiento], [Foto], [IdPais], [IdDeporte], [Logros]) VALUES ( N'Rivera', N'Hezly', CAST(N'2008-01-01' AS Date), N'https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Hezly_Rivera_%28USA%29_2024.jpg/235px-Hezly_Rivera_%28USA%29_2024.jpg', 2, 24, N'Medallista de oro en gimnasia, atleta más joven del equipo')
INSERT [dbo].[Deportistas] ([Apellido], [Nombre], [FechaNacimiento], [Foto], [IdPais], [IdDeporte], [Logros]) VALUES ( N'Bolt', N'Usain', CAST(N'1986-08-21' AS Date), N'https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/Usain_Bolt_after_4_%C3%97_100_m_Rio_2016.jpg/800px-Usain_Bolt_after_4_%C3%97_100_m_Rio_2016.jpg', 12, 8, N'Medallista de oro en atletismo, 8 veces campeón olímpico')
INSERT [dbo].[Deportistas] ([Apellido], [Nombre], [FechaNacimiento], [Foto], [IdPais], [IdDeporte], [Logros]) VALUES ( N'Neymar', N'Jr.', CAST(N'1992-02-05' AS Date), N'https://upload.wikimedia.org/wikipedia/commons/8/83/Bra-Cos_%281%29_%28cropped%29.jpg', 41, 9, N'Medallista de oro en fútbol, campeón olímpico')
INSERT [dbo].[Deportistas] ([Apellido], [Nombre], [FechaNacimiento], [Foto], [IdPais], [IdDeporte], [Logros]) VALUES ( N'Yao', N'Ming', CAST(N'1980-09-12' AS Date), N'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/YaoMingonoffense2.jpg/800px-YaoMingonoffense2.jpg', 54, 10, N'Medallista de oro en baloncesto, 4 veces medallista olímpico')
INSERT [dbo].[Deportistas] ([Apellido], [Nombre], [FechaNacimiento], [Foto], [IdPais], [IdDeporte], [Logros]) VALUES ( N'Federer', N'Roger', CAST(N'1981-08-08' AS Date), N'https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Roger_Federer_2012_Doha.jpg/245px-Roger_Federer_2012_Doha.jpg', 65, 12, N'Medallista de oro en tenis, 20 veces campeón de Grand Slam')
INSERT [dbo].[Deportistas] ([Apellido], [Nombre], [FechaNacimiento], [Foto], [IdPais], [IdDeporte], [Logros]) VALUES ( N'Pele', N'', CAST(N'1940-10-23' AS Date), N'https://upload.wikimedia.org/wikipedia/commons/5/5e/Pele_con_brasil_%28cropped%29.jpg', 41, 9, N'Medallista de oro en fútbol, 3 veces campeón del mundo')
INSERT [dbo].[Deportistas] ([Apellido], [Nombre], [FechaNacimiento], [Foto], [IdPais], [IdDeporte], [Logros]) VALUES ( N'Bencic', N'Belinda', CAST(N'1997-03-10' AS Date), N'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Belinda_Bencic_%282023_US_Open%29_09.jpg/800px-Belinda_Bencic_%282023_US_Open%29_09.jpg', 65, 12, N'Medallista de oro en tenis, campeona olímpica en individuales y dobles')
INSERT [dbo].[Deportistas] ([Apellido], [Nombre], [FechaNacimiento], [Foto], [IdPais], [IdDeporte], [Logros]) VALUES ( N'Kipchoge', N'Eliud', CAST(N'1984-11-05' AS Date), N'https://upload.wikimedia.org/wikipedia/commons/a/ad/Eliud_Kipchoge_%28KEN%29_2015.jpg', 66s, 8, N'Medallista de oro en maratón, 2 veces campeón olímpico')*/